name: Compress Ungoogled Chromium
on: [push]


jobs:
  compress:
    name: zstd Ungoogled Chromium
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: fetch ungoogled chromium
      run: wget https://github.com/ungoogled-software/ungoogled-chromium-macos/releases/download/126.0.6478.182-1.1/ungoogled-chromium_126.0.6478.182-1.1_x86-64-macos.dmg
   
    - name: update zstd
      run: brew install zstd

    - name: compress ungoogled chromium with tar
      run: tar cf ./ungoogled-chromium_126.0.6478.182-1.1_x86-64-macos.dmg.tar ungoogled-chromium_126.0.6478.182-1.1_x86-64-macos.dmg

    - name: compress ungoogled chromium with zstd
      run: zstd -19 ungoogled-chromium_126.0.6478.182-1.1_x86-64-macos.dmg.tar

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        compression-level: 9
        path: ./ungoogled-chromium_126.0.6478.182-1.1_x86-64-macos.dmg.tar.zst
     
   
  
